export const companies = [
  {
    id: "c-microsoft",
    name: "Microsoft",
    industry: "Technology",
    description: "Global technology leader in cloud computing, AI, and enterprise software.",
    employeeCount: 221000,
    website: "https://microsoft.com",
  },
  {
    id: "c-apple",
    name: "Apple",
    industry: "Consumer Electronics",
    description: "World's most valuable company, known for iPhone, Mac, and services ecosystem.",
    employeeCount: 164000,
    website: "https://apple.com",
  },
  {
    id: "c-amazon",
    name: "Amazon",
    industry: "E-commerce / Cloud",
    description: "Global leader in e-commerce and cloud infrastructure (AWS).",
    employeeCount: 1540000,
    website: "https://amazon.com",
  },
  {
    id: "c-jpmorgan",
    name: "JPMorgan Chase",
    industry: "Financial Services",
    description: "Largest bank in the US by assets, leading investment bank and financial services firm.",
    employeeCount: 309000,
    website: "https://jpmorganchase.com",
  },
  {
    id: "c-google",
    name: "Google (Alphabet)",
    industry: "Technology",
    description: "Dominant search engine, cloud platform, and AI research powerhouse.",
    employeeCount: 182000,
    website: "https://abc.xyz",
  },
  {
    id: "c-meta",
    name: "Meta Platforms",
    industry: "Social Media / Technology",
    description: "Parent company of Facebook, Instagram, WhatsApp; investing heavily in metaverse and AI.",
    employeeCount: 67000,
    website: "https://meta.com",
  },
  {
    id: "c-nvidia",
    name: "Nvidia",
    industry: "Semiconductors",
    description: "Leading GPU and AI chip manufacturer powering the AI revolution.",
    employeeCount: 29600,
    website: "https://nvidia.com",
  },
  {
    id: "c-salesforce",
    name: "Salesforce",
    industry: "Enterprise Software",
    description: "World's #1 CRM platform, expanding into AI-powered enterprise solutions.",
    employeeCount: 73000,
    website: "https://salesforce.com",
  },
  {
    id: "c-adobe",
    name: "Adobe",
    industry: "Software",
    description: "Creative and document management software leader, pioneering generative AI in creative tools.",
    employeeCount: 30000,
    website: "https://adobe.com",
  },
  {
    id: "c-netflix",
    name: "Netflix",
    industry: "Entertainment / Streaming",
    description: "Global streaming entertainment leader with 260M+ subscribers.",
    employeeCount: 13000,
    website: "https://netflix.com",
  },
  {
    id: "c-nike",
    name: "Nike",
    industry: "Consumer Goods / Apparel",
    description: "World's largest athletic footwear and apparel company.",
    employeeCount: 79400,
    website: "https://nike.com",
  },
  {
    id: "c-pepsico",
    name: "PepsiCo",
    industry: "Food & Beverage",
    description: "Global food and beverage giant with brands including Pepsi, Frito-Lay, Gatorade.",
    employeeCount: 315000,
    website: "https://pepsico.com",
  },
];
